# Generated by Django 3.2.5 on 2022-03-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='i',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
